name: voyager_list
description: Voyager add-on package. Facilitates dynamic mapping of a list of arbitrary objects to a ListWiew.
version: 0.3.0
homepage: https://github.com/vishna/voyager_list

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  voyager:
    git:
      url: https://github.com/eyeem/voyager.git
      ref: v3.0.2

  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
